# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "localization-middleware"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["E-Max"]
  s.date = "2012-08-26"
  s.description = "Middleware that plays the connection between the url and I18n."
  s.email = "max@studentify.nl"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rvmrc",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/localization-middleware.rb",
    "lib/localization_middleware.rb",
    "test/middleware_test.rb",
    "test/test_app/.components",
    "test/test_app/app/app.rb",
    "test/test_app/app/controllers/main.rb",
    "test/test_app/app/controllers/user.rb",
    "test/test_app/app/helpers/application_helper.rb",
    "test/test_app/config.ru",
    "test/test_app/config/apps.rb",
    "test/test_app/config/boot.rb",
    "test/test_app/public/favicon.ico",
    "test/test_helper.rb"
  ]
  s.homepage = "http://github.com/kot-begemot/localization-middleware"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Localize your application via url"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0"])
    else
      s.add_dependency(%q<i18n>, [">= 0"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0"])
  end
end

